version: '3.4'

services:
  dfcxdiscord:
    image: dfcxdiscord
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: 
      - .env

